<p class='notebook_header'><b>CS 309 - Robot Learning</b></p>
<p class='notebook_header'>Homework 1</p>
<hr class='separate' />

<p class='section_header'><b>Part 1: Linear Algebra</b></p>

Implement the following matrix/vector functions using NumPy operations.

If the function's operation isn't possible for matrix or vector inputs, return None.

In [44]:
import numpy as np

In [45]:
def add(a, b):
    return np.add(a,b);

def subtract(a, b):
    return np.subtract(a, b);

def multiply(a, b):
    return np.matmul(a,b);

def divide(a, b):
    return None;

def transpose(a):
    return a.T;

def two_norm(a):
    return np.linalg.norm(a, 2);

<p>Using your code from above, solve the following equations. If an operation isn't possible, put None or comment with "Not Possible".</p>

$$
u = \begin{bmatrix} 2 \\ 3 \\ 9 \end{bmatrix}, \:
v = \begin{bmatrix} -2 \\ 1 \\ 8 \end{bmatrix}
$$  


In [46]:
u = np.array([
    [2],
    [3],
    [9]
])

v = np.array([
    [-2],
    [1],
    [8]
])

$$ u + v = \begin{bmatrix} 0 \\ 4 \\ 17 \end{bmatrix} $$  

$$ u - v = \begin{bmatrix} 4 \\ 2 \\ 1 \end{bmatrix} $$  

$$ u * v = \text{Not Possible} $$  

$$ u \div v = \text{Not Possible} $$  


In [47]:
# YOUR CODE HERE

u_plus_v = add(u,v)

u_minus_v = subtract(u,v)

u_mult_v = None # not possible, dimensions of u and v are both (3,1) so multiplication can't happen

u_div_v = divide(u,v) # this returns None anyways, not possible since dividing matrices isn't allowed

$$ u^{\;T} * v = \begin{bmatrix} 71 \end{bmatrix} $$  

$$ u * v^{\;T} = \begin{bmatrix} -4 & 2 & 16 \\ -6 & 3 & 24 \\ -18 & 9 & 72 \end{bmatrix} $$  

$$ u^{\;T} * u = \begin{bmatrix} 94 \end{bmatrix} $$  

$$ \left \| u \right \|_{2}^{2} = 94.0 $$  


In [48]:
# YOUR CODE HERE

u_transpose_v = multiply(transpose(u), v)
print(u_transpose_v)

u_v_tranpose = multiply(u, transpose(v))
print(u_v_tranpose)

u_tranpose_u = multiply(transpose(u), u)
print(u_tranpose_u)

two_norm_u = two_norm(u) ** 2
print(two_norm_u)

[[71]]
[[ -4   2  16]
 [ -6   3  24]
 [-18   9  72]]
[[94]]
94.00000000000001


<hr class='light-separate' />

$$
A = \begin{bmatrix} 1 & 6 & 5\\ 0 & -4 & -1\\ 7 & 2 & 3 \end{bmatrix}, \: 
B = \begin{bmatrix} 3 & 1 & 1\\ 4 & -1 & 7\\ 7 & 0 & 0 \end{bmatrix}
$$  


$$ A + B = \begin{bmatrix} 4 & 7 & 6 \\ 4 & -5 & 6 \\ 14 & 2 & 3 \end{bmatrix} $$  

$$ A - B = \begin{bmatrix} -2 & 5 & 4 \\ -4 & -3 & -8 \\ 0 & 2 & 3 \end{bmatrix} $$  

$$ A * B = \begin{bmatrix} 62 & -5 & 43 \\ -23 & 4 & -28 \\ 50 & 5 & 21 \end{bmatrix} $$  

$$ A \div B = \text{Not Possible} $$  


In [49]:
# YOUR CODE HERE

a = np.array([
    [1, 6, 5],
    [0, -4, -1],
    [7, 2, 3]
])

b = np.array([
    [3, 1, 1],
    [4, -1, 7],
    [7, 0, 0]
])

a_plus_b = add(a,b)
print(a_plus_b)

a_minus_b = subtract(a,b)
print(a_minus_b)

a_mult_b = multiply(a,b)
print(a_mult_b)

a_div_b = divide(a,b)
print(a_div_b)

[[ 4  7  6]
 [ 4 -5  6]
 [14  2  3]]
[[-2  5  4]
 [-4 -3 -8]
 [ 0  2  3]]
[[ 62  -5  43]
 [-23   4 -28]
 [ 50   5  21]]
None


<hr class='light-separate' />

$$
C = \begin{bmatrix} 5 & 1 \\ -1 & 7 \\ 3 & 0 \end{bmatrix}
$$  


In [50]:
c = np.array([[5, 1],
              [-1, 7],
              [3, 0]])

Right Pseudo Inverse of C:
$$
\begin{align}
    &= C^T(C C^T)^{-1}\\
    &=
    \begin{bmatrix}
    0.3125 & -0.0078125 & 0.25 \\
    0.05859375 & 0.14208984 & 0.0390625
    \end{bmatrix}
\end{align}
$$  

Left Pseudo Inverse of C:
$$
\begin{align}
&= (C^T C)^{-1} C^T \\
&=
\begin{bmatrix}
0.1443299 & -0.02061856 & 0.08591065 \\
0.0257732 & 0.13917526 & 0.00343643
\end{bmatrix}
\end{align}
$$  


In [51]:
# YOUR CODE HERE
right_pinv = multiply(transpose(c), np.linalg.inv(multiply(c, transpose(c))))
print(right_pinv)

left_pinv = multiply(np.linalg.inv(multiply(transpose(c), c)), transpose(c))
print(left_pinv)

[[ 0.3125     -0.0078125   0.25      ]
 [ 0.05859375  0.14208984  0.0390625 ]]
[[ 0.1443299  -0.02061856  0.08591065]
 [ 0.0257732   0.13917526  0.00343643]]


<hr class='separate' />

<p class='section_header'><b>Part 2: Regression</b></p>

**Write** the equation for Ordinary Least Squares below. 

$$
\hat{\Theta} = ((X^T \ X)^{-1} \ X^T) \ Y \\
$$

**Explain** Ordinary Least Squares in terms of what it optimizes.

Ordinary Least Squares (OLS) tries to find the line of best fit (in any dimension) in a given dataset. It does this by trying to minimize the distance between the predicted value in the line of best fit and the actual, given value, for each point in the dataset. The goal is to find a $\hat{\Theta}$ representing the optimum slopes and intercepts for the function to represent the line of best fit. Here, $\hat{\Theta}$ will represent the optimum line of best fit and $\underline{\Theta}$ will represent an imperfect line of best fit.

In mathematical terms, the for every data point $i$, the predicted value is $x_i^T \underline{\Theta}$ and the ground truth value is $y_i$. To this minimization goal, a few modifications are added. The goal is squared to ensure that the magnitude of the error is being minimized. It is multiplied by $\frac{1}{N}$ to aid in the math when finding the optimal $\hat{\Theta}$.

Then, summing the minimization goal over all datapoints and creating a function $argmin(\underline{\Theta})$ to accept the argument $\underline{\Theta}$ and return the optimum $\hat{\Theta}$ that minimizes the optimization goal, we have:

$$\hat{\Theta} = argmin(\underline{\Theta}) \ \frac{1}{N} \ \sum_{i}^{N} [X_i^T - Y_i]^2$$

After doing some calculus, this simplifies to:
$$
\hat{\Theta} = ((X^T \ X)^{-1} \ X^T) \ Y \\
$$



In [54]:
# Don't change this cell!
# Load in the data about the study on students
train = np.loadtxt('train.csv', delimiter=',')
x_0, x_1, x_2, y = train.T
X_train = np.array([x_0, x_1, x_2]).T
Y_train = np.expand_dims(y, 1)

test = np.loadtxt('test.csv', delimiter=',')
x_0, x_1, x_2, y = test.T
X_test = np.array([x_0, x_1, x_2]).T
Y_test = np.expand_dims(y, 1)

There was an imaginary study done on 101 students at Crest University. The study surveyed students for the amount they have spent on electronics, books, pencils, and foods. 

Given that the **amount students spend on electronics ($Y$)** is linearly related to the **amount they spend on books ($ X_{0} $), pencils ($ X_{1}$)**, and **food ($ X_{2}$)**, 
**implement** the Ordinary Least Squares method to model this regression problem.

The data is read in from the previous cell code. **X_train** has the input features, while **Y_train** has corresponding target outputs.

After finding a solution, try to measure the error between your predictions and the ground truth. 

In [57]:
# TODO: Create code for OLS here. DO NOT use any other libraries in your first implementation.
# TODO: Plot your regression line over the input points.

def OLS(X, y):
    pseudo_inv = multiply(np.linalg.inv(multiply(X.T, X)), X.T)
    theta = multiply(pseudo_inv, y)
    return theta

# multiply X and theta to get the prediction
def get_prediction(X, theta):
    return multiply(X.T, theta)

# 
def get_error(prediction, ground_truth):
    assert(np.shape(prediction) == np.shape(ground_truth))
    return two_norm(subtract(prediction, ground_truth))

# TODO: check against training data
theta = OLS(X_train,Y_train)
# error = get_error(get_prediction(X_train, theta), Y_train)
# print(error)

# # TODO: test your model on testing data
# theta = OLS(X_train, Y_train)
# error = get_error(get_prediction(X_test, theta), Y_test)
# print(error)

**Explain** what collinearity is.

**(TODO: Write Here)**

**Write** the equation for Ridge Regression below. 

**(TODO: Write Here)**

**Explain** what the purpose ridge regression and its advantages and disadvantages over OLS.

**(TODO: Write Here)**

**Implement** your regression model with ridge regression below.

In [140]:
# TODO: Create code for Ridge Regression here. DO NOT use any other libraries
# TODO: Plot your regression line over the input points.

def RR(X, y, ridge=0.001):
    pass

# TODO: check against training data
theta = RR(X_train,Y_train)


# TODO: test your model on testing data


**Explain** the differences ridge regression created for theta compared to OLS, and why these differences even existed. Also try different values for the ridge parameters and describe how they effect your results.

**(TODO: Write here)**

There are other regularizers other than ridge regression, such as LASSO. **Explain** the differences between LASSO and Ridge Regression and how it changes the solution mathematically.

**(TODO: Write here)**

In [144]:
# TODO: Create code for LASSO here
# TODO: Plot your regression line over the input points. 

def LASSO(X, y, ridge=.001):
    pass

# TODO: check against training data
theta = LASSO(X_train,Y_train)

# TODO: check against testing data

**Explain** the effect elastic nets had on your values for theta compared to OLS. Also try different values for the ridge parameters and describe how they effect your results.

**(TODO: Write here)**

**Explain** the differences between LASSO, Ridge Regression and Elastic Nets and how it changes the solution mathematically.

**(TODO: Write here)**

In [146]:
# TODO: Create code for Elastic Nets here. You can use a library such as scipy
# TODO: Plot your regression line over the input points.

def EN(X,y):
    pass

# TODO: check against training data
theta = EN(X_train,Y_train)

# TODO: check against testing data

What is the purpose of a regularizer?

**(TODO: Write here)**

Give two examples where a regularizer would give more robust models.

**(TODO: Write here)**

Explain with reference to the dataset why a regularizer achieved better performance than OLS.

**(TODO: Write here)**

<hr class='light-separate' />

Implement feature transformation to fit a line to the curve generated from the .csv file.

In [2]:
X = np.genfromtxt('feature_transform.csv', delimiter=',')
y = X[:,2].reshape(500, 1)
X = X[:,:2]

In [ ]:
# TODO: Write the lambda function phi which will transform X
# TODO: Plot the transformation and the resulting line after transforming

phi = "fill in with lambda function"
import matplotlib.pyplot as plt
plt.scatter(X[:,0],y,color=(0.0,0.5,0.0))
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

<hr class='light-separate' />

Recall what you learned about polynomial regression and explain what is happening to the model as you increase the degrees. Run the cell below and use the slider to help you.

**(TODO: Write here)**

In [ ]:
# DO NOT ALTER

import pandas as pd
import ipywidgets as widgets
from ipywidgets import interact
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline

boston = datasets.load_boston()
data = pd.DataFrame(boston.data,columns=boston.feature_names)
data = pd.concat([data,pd.Series(boston.target,name='MEDV')],axis=1)

X = data[['LSTAT']].values
y = data['MEDV']

x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42, shuffle=True)

temp = pd.DataFrame({'x':x_train.reshape(1, 354)[0], 'y':y_train})
temp = temp.sort_values('x')
x_train = temp['x'].values.reshape(354,1)
y_train = temp['y'].values

temp = pd.DataFrame({'x':x_test.reshape(1, 152)[0], 'y':y_test})
temp = temp.sort_values('x')
x_test = temp['x'].values.reshape(152,1)
y_test = temp['y'].values

def f(degree):
    model = make_pipeline(PolynomialFeatures(degree), LinearRegression())
    model.fit(x_train,y_train)
    y_plot = model.predict(x_test)
    
    plt.scatter(x_train, y_train, s=10, color='red', alpha=.3)
    plt.scatter(x_test, y_test, s=10)

    test_sr = (y_test - y_plot)**2
    test_ssr = test_sr.sum()
    test_asr = test_ssr/len(test_sr)
    
    y_plot_train = model.predict(x_train)
    train_sr = (y_train - y_plot_train)**2
    train_ssr = train_sr.sum()
    train_asr = train_ssr/len(train_sr)
    
    plt.plot(x_test, y_plot, label="degree %d" % degree + '; Test Error: %.2f' % test_asr + '; Train Error: %.2f' % train_asr, color='green')
    plt.legend(loc='upper right')
    plt.show()
    
interact(f, degree = widgets.IntSlider(min=1, max=20, step=1, value=1))